# Publish the Nix flake outputs to Cachix
name: Cachix
on:
  push:
    branches:
      - driver-new
      - master

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install Nix(ummm, akshually Lix)
      uses: samueldr/lix-gha-installer-action@latest
      with: 
        extra_nix_config: |
          substituters = https://darshancommits.cachix.org
          trusted-public-keys = darshancommits.cachix.org-1:aITLC4uLnoX/hHdms6Jfj60BkH9e21DxGPz/IB0YMvw=

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v16
      with:
        name: darshancommits
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build nix flake
      run: |
        cachix watch-exec darshancommits -- \
          nix build -L --print-build-logs 
